caelum/mamute

- pom.xml
- src/integration/java/org/mamute/integration/scene/AcceptanceTestBase.java
Selenium 2.41 is not compatible anymore with latest Firefox so Unit tests can't be run with the new Firefox
See: https://code.google.com/p/selenium/issues/detail?id=7823
> Bumping Selenium version and Firefox version used for testing.

- src/main/resources/production/hibernate.cfg.xml.example
- src/main/webapp/WEB-INF/tags/header.tag
* setting UTF8 meta tag in header - not having this tag set may cause browser to incorrectly render UTF-8 characters part of certain languages
* adding UTF8 support to JDBC path in hibernate template for production
> Better UTF 8 support : meta header and default production config

- src/main/resources/mamute-messages.properties
- src/main/resources/mamute.properties
- src/main/webapp/WEB-INF/jsp/theme/default/header.jspf
- src/main/webapp/WEB-INF/jsp/userProfile/editProfile.jsp
- src/main/webapp/WEB-INF/tags/RankingUser.tag
- src/main/webapp/WEB-INF/tags/completeUser.tag
- src/main/webapp/WEB-INF/tags/userProfileTab.tag
Bug was introduced in ce2f977480ac27e9da8b08622d76e20cbeef0b0e 
Half of the code in that commit assumes that gravatar.avatar.url has been added to the environment file, other half assumes the language file.
This also breakes the unit tests.
Moving the key to environment file and fixing all the templates to use it.
> Fixes a gravatar bug breaking the tests 

- src/main/java/org/mamute/auth/GoogleAuthService.java
- src/main/java/org/mamute/controllers/GoogleAuthController.java
- src/main/java/org/mamute/model/User.java
- src/test/java/org/mamute/model/UserTest.java
* use parameter name that will actually get passed back. Currently "redirect" is getting stripped by google so we don't get it back
* respect requested size for google avatars
> Google Auth improvements

- src/main/resources/mamute.properties
- src/main/webapp/WEB-INF/jsp/coda.jspf
- src/main/webapp/WEB-INF/jsp/theme/default/header.jspf
Intro can now be disabled, if desired.
Defaults to enabled, so it is backwards compatible
> Allow intro tutorial to be optional feature

- src/main/java/org/mamute/auth/LDAPApi.java
- src/main/resources/mamute.properties
Due to LDAP server restrictions in our environment, we can only connect to the LDAP via SSL. This little patch adds the ability to choose whether to connect via SSL or not. Default is connecting without SSL.
The optional configuration flag in mamute.properties is:
ldap.useSSL=true
> Adding LDAP SSL option

- src/main/webapp/WEB-INF/tags/header.tag
Adding this include tag as a first thing after opening of the <BODY> HTML tag allows us to include JavaScripts that need to be injected at the very top of the BODY.
Adding empty include in the project which developers can override with their own version in the ``custom`` template folder.
> Allow including JavaScripts as a first thing in the body

- src/main/resources/mamute.properties
- src/main/webapp/WEB-INF/jsp/theme/default/header.jspf
- src/main/webapp/WEB-INF/tags/userProfileTab.tag
As many websites are moving away from exposing the logout button too much, this pull request enables site owner to move the 'logout' button out of the main menu into the user profile.
> Add ability to move logout link to user profile

- newrelic/newrelic.yml
This removes your guys' New Relic licence key from the project.
I would go as far as to consider removing entire New Relic folder from the project - this shouldn't be part of the project, at most it's dependency. I am also using New Relic, but have installed it in a separate folder and am injecting the directory in the run script.
> Remove new relic key from public repo

- src/main/webapp/WEB-INF/jsp/theme/default/header.jspf
This allows site owners to use mainTags functionality without overriding a template file.
I plan to prepare PR to move this to database, but don't have time short-term to do it
> Extract main tags from the translate file

- src/main/resources/routes.properties
- src/main/resources/routes.pt-BR.properties
- src/main/webapp/WEB-INF/jsp/coda.jspf
- src/main/webapp/assets/js/fileuploader.js
Currently the attachment upload does not work because jQuery sends the
data to "/attachments" (even after changing the url property to include
the trailing slash in "/attachments/"). Thus I also renamed the route
to /attachments/upload.
This fixes in-house file uploads.
> Fix attachment upload

- src/main/webapp/assets/less/ranking.less
Whenever there are only few users (this usually happens on the last
page) then each user (ranking-item) is getting very small.
This is because the ranking container shrinks automatically when there
are only a few items and the items themselves are using a relative size.
This is fixed by ensuring that the ranking container always uses the
full width, so the ranking-items are always using 15% of the full width.
> Fix the layout of the ranking view when there are only a few users

- pom.xml
Had hard time running mvn package from shell on Mac (worked fine with Ubuntu).
The only thing that really helped was bumping maven plugin.
I am not sure it makes sense to push this to master, so feel free to reject the PR if you think it's dangerous.
> Bump the maven plugin version to work nice with Mac/Java 1.7

- src/main/java/org/mamute/auth/LDAPApi.java
- src/main/java/org/mamute/auth/LdapSSOFilter.java
This commit implements a Single Sign On for Mamute which loads all required user information for a trusted SSO user name from LDAP. 
We implemented this for use in an Active Directory Environment with Kerberos authentication. To have this working with Mamute, we set up an Apache httpd dealing with Kerberos, setting REMOTE_USER, and forwarding this to an Apache Tomcat. Mamute runs on the Tomcat.
This is not yet tested with Jetty, as I really could not figure out how to easily pass the REMOTE_USER to Jetty WITHOUT using mod_ajp.
To enable SSO, add to your [environment].properties (together with all required LDAP configuration):
ldap.sso = true
> Implements LDAP based Single Sign On

- pom.xml
Updated Maven version to 3.3 (to newer version than pull request 132) left compile target at 1.7
Removed com.keyboardsamurais.maven as no longer necessary in newer Maven
versions
Updated Jacoco version for Java 8 (same as pull request 191 by
XDarklight)
Merged duplicate entries to prevent build warnings
Added maven-clean-plugin version to prevent build warning
Minor update of Solr version to 4.10 (note updating to Solr 5 causes
problems with dependency injection)
> Updated maven pom

- src/main/webapp/WEB-INF/tags/RankingUser.tag
The bug can be seen here: http://meta.mamute.org/ranking/grunt
Image URLs are starting with
```
<span class='i18n_missing_key'>gravatar.avatar.url</span>/avatar/..."
```
> Fix the gravatar URL on the tag ranking page

- src/main/resources/mamute-messages_de.properties
Flagging a question or answer means reporting it to the moderator team.
Thus it should be translated as "melden" instead of "markieren".
CC: @cpfeiffer
> Fix the German translation for "flag question/answer"

- src/main/java/org/mamute/dao/ReputationEventDAO.java
- src/test/java/org/mamute/dao/ReputationEventDAOTest.java
Original stacktrace:
java.lang.NullPointerException
at org.mamute.dto.KarmaByContextHistory.<init>(KarmaByContextHistory.java:19)
at org.mamute.dao.ReputationEventDAO.karmaByContext(ReputationEventDAO.java:79)
at org.mamute.dao.ReputationEventDAO.karmaWonByQuestion(ReputationEventDAO.java:62)
> Fix viewing profiles with deleted questions

- src/main/java/org/mamute/brutauth/auth/rules/GlobalShouldBeLoggedRule.java
- src/main/java/org/mamute/controllers/AuthController.java
- src/main/java/org/mamute/controllers/FacebookAuthController.java
- src/main/java/org/mamute/controllers/ForgotPasswordController.java
- src/main/java/org/mamute/controllers/GoogleAuthController.java
- src/main/java/org/mamute/controllers/MessagesController.java
- src/main/java/org/mamute/controllers/SignupController.java
- src/main/resources/mamute.properties
This makes it possible to use mamute for private communities. Setting
the new feature toggle "feature.login.required" to "true" means that
users have to sign in before they can see questions.
> Add a feature toggle to enable private communities

- src/main/java/org/mamute/infra/ModelUrlMapping.java
- src/test/java/org/mamute/infra/ModelUrlMappingTest.java
The merge of PR #187 broke the up- and downvote functionality because
now the simple-name of the "related item" class is passed to the server.
This extends ModelUrlMapping to not only handle the translated names but
also the simple class names. The upvote/downvote URLs are only called
from JavaScript (thus they are not seen by any user, except for those
who are looking at the requests in their browser's development tools).
> Fix upvote/downvote functionality

- src/main/java/br/com/caelum/vraptor/server/VRaptorServer.java
Allows setting Jetty HOST in a fashion similar to setting of PORT
Needed to be able to deploy to Openshift
> Jetty server to use HOST system env variable if available

- src/main/java/org/mamute/notification/NotificationMailer.java
- src/main/resources/mamute-messages.properties
- src/main/resources/mamute-messages_de.properties
- src/main/resources/mamute-messages_pt_BR.properties
The first commit fixes an exception when sending the comment notification mail:
```
java.lang.RuntimeException: java.lang.IllegalArgumentException: Subject not defined for email template : comment_notification_mail
at br.com.caelum.vraptor.simplemail.template.DefaultTemplateMail.prepareEmail(DefaultTemplateMail.java:99)
at br.com.caelum.vraptor.simplemail.template.DefaultTemplateMail.to(DefaultTemplateMail.java:66)
at org.mamute.notification.NotificationMailer.buildEmail(NotificationMailer.java:72)
at org.mamute.notification.NotificationMailer.send(NotificationMailer.java:51)
at org.mamute.notification.NotificationManager$SendNotifications$1.insideRequest(NotificationManager.java:84)
at org.mamute.notification.NotificationManager$SendNotifications$1.insideRequest(NotificationManager.java:1 …
```
> Fix comment notification mail

- src/main/webapp/WEB-INF/jsp/coda.jspf
This prevents a small information leak where filepicker.io gets some information about mamute users (IP, browser, etc) even when the inhouse upload is enabled.
> Don't include the filepicker.io JS when using inhouse file upload

- src/main/webapp/WEB-INF/jsp/coda.jspf
- src/main/webapp/assets/js/fileuploader.js
This fixes deleting attachments on tomcat where HTTP DELETE (and PUT)
are disabled by default. Enabling them is also not possible because that
would allow users to delete attachments if they know the id of the
attachment on the file-system (for example with curl, by running
curl -X DELETE http://mamute.local/attachments/1).
> Use HTTP POST when deleting attachments

- src/main/java/org/mamute/providers/DefaultViewObjects.java
Use the configured host and protocol instead of the one
from the headers.
When using the request's host and a hardcoded protocol ("http"), the resulting URLs would be wrong, especially when using a proxy server.
> Fix URL in pagers when using e.g. ssl proxy

- src/main/java/org/mamute/brutauth/auth/handlers/LoggedHandler.java
- src/main/java/org/mamute/controllers/AuthController.java
- src/main/webapp/WEB-INF/tags/header.tag
In case of LDAP SSO the user is trying to access Mamute (while still not
authenticated via LDAP SSO). The user is then redirected to the login
where LDAP SSO is enabled. When the request reaches AuthController the
user is already logged in and redirected to the page where he/she came
from. Unfortunately the "you must be logged in" message was still shown
in this case. Fix this by clearing the message in such cases.
> Hide the "login required" message after LDAP SSO

- src/main/java/org/mamute/auth/LDAPApi.java
The LDAP authentication plugin was written assuming that the objectClass of a user was simply "user". In our organization we actually use the LDAP schema "inetOrgPerson". This update modifies the class to provide a new configuration option `ldap.userObjectClass` and allows to specify the objectClass of users. The default value will be as it has been ("`user`").
> Add configurable objectClass for LDAP lookups

- src/main/java/org/mamute/auth/LDAPApi.java
- src/main/resources/mamute.properties
In order for our moderatorGroup to work, we need the memberOf LDAP attribute to be searched for a given user to see if they are a moderator. However, in our LDAP server, the memberOf attribute on a user is a operational attribute (as opposed to a user attribute), so it wasn't coming back with the normal .lookup() method. This patch leaves the existing behavior in as the default, but adds the ability to pull back all attributes (equivalent of * and + in LDAP).
> Add option for LDAP to pull all attributes for user entry

- src/main/java/org/mamute/model/User.java
- src/main/java/org/mamute/providers/DefaultViewObjects.java
- src/main/resources/mamute.properties
- src/main/webapp/WEB-INF/jsp/theme/default/header.jspf
- src/test/java/org/mamute/model/UserTest.java
PR for a handful of small issues: 
1. Gravatar/Robohash image will now use https by default. Also in my configuration I use a protocol-relative for gravatar so that it will use https if that's what the current protocol is. As an example, here's my value: `gravatar.avatar.url=//www.gravatar.com`
2. There was a bug with the redirectUrl when logging in from a question directly. It was adding an extra slash and going nowhere. The URI will always start with a forward slash so we don't need it. The redirectUrl isn't used on the main login form, so there's no effect there
3. Added new option to hide news navigation link
4. Update UserTest unit test to reflect https URL in robohash
> SSL, news hiding, and login redirect fixes

- src/main/java/org/mamute/dao/TagDAO.java
- src/test/java/org/mamute/dao/DatabaseTestCase.java
- src/test/java/org/mamute/dao/TagDAOTest.java
The `should_load_recent_tags_used` test sometimes produced a false negative because the ordering of the tags was non-deterministic.  Fix the ordering by adding a second sort field (the name of the tag).
> Fix flaky test
