src/main/java/org/mamute/controllers/UserProfileController.java, src/main/java/org/mamute/model/User.java, src/main/migrations/org/mamute/migration/all/M011AddUserAvatar.java, src/main/migrations/org/mamute/migration/all/M012AddUserAvatar.java, src/main/resources/mamute-messages.properties, src/main/resources/routes.properties, src/main/webapp/WEB-INF/jsp/coda.jspf, src/main/webapp/WEB-INF/jsp/userProfile/editProfile.jsp, src/main/webapp/assets/js/avatarupload.js
Using the new upload API, users can now upload their own avatars instead of using gravatar.
=> Local avatars

src/main/java/org/mamute/controllers/QuestionController.java, src/main/java/org/mamute/controllers/UserProfileController.java, src/main/java/org/mamute/dao/UserDAO.java, src/main/java/org/mamute/dto/UserPersonalInfo.java, src/main/java/org/mamute/event/QuestionCreated.java, src/main/java/org/mamute/mail/NewQuestionMailer.java, src/main/java/org/mamute/model/User.java, src/main/java/org/mamute/observer/SubscribeUsersToNewQuestion.java, src/main/migrations/org/mamute/migration/all/M013AddReceiveAllUpdatesToUser.java, src/main/resources/mamute-messages.properties, src/main/resources/templates/new_question_notification.ftl, src/main/webapp/WEB-INF/jsp/userProfile/editProfile.jsp, src/test/java/org/mamute/mail/NewQuestionMailerTest.java
With this PR, users can choose to receive updates of all new questions (this will be very useful for us to keep track of meta.mamute.org). Can you take a look, @leocwolter?
=> Email updates

src/main/java/org/mamute/controllers/HistoryController.java, src/main/java/org/mamute/controllers/UserProfileController.java, src/main/java/org/mamute/infra/ModelUrlMapping.java, src/main/resources/mamute-messages.properties, src/main/resources/mamute-messages_pt_BR.properties, src/main/webapp/WEB-INF/jsp/error/500.jsp, src/main/webapp/WEB-INF/jsp/history/unmoderated.jsp, src/main/webapp/WEB-INF/jsp/theme/default/header.jspf, src/main/webapp/WEB-INF/jsp/userProfile/showProfile.jsp, src/main/webapp/WEB-INF/tags/answerWith.tag, src/main/webapp/WEB-INF/tags/commentWith.tag, src/main/webapp/WEB-INF/tags/newsWith.tag, src/main/webapp/WEB-INF/tags/questionWith.tag, src/main/webapp/WEB-INF/tags/userProfileAdvancedPostData.tag, src/main/webapp/WEB-INF/tags/userProfilePagination.tag
Due to hard-coded types in the JSP files, the routing file was not fully working (e.g. for some routes with answers, questions etc) when internationalized. This pull request:
* changes majority of hard-coded types to be derived from localization file instead
* moves hard-coded Error 500 to localization file
=> Improved localization

src/main/webapp/WEB-INF/jsp/coda.jspf, src/main/webapp/WEB-INF/tags/fileUploader.tag, src/main/webapp/assets/js/fileuploader.js
As discussed we dicussed, @MatejBalantic 
https://github.com/caelum/mamute/commit/552adfa2908b773de02a2817a535c400de32b252#commitcomment-11227240
=> i18n of attachments link

src/main/webapp/WEB-INF/tags/completeUser.tag
This will create a link on a user avatar that points to his profile.
=> Link to user profile from avatars

src/main/webapp/WEB-INF/jsp/userProfile/editProfile.jsp
This link is pointless as it displays "EDIT PROFILE" button on the edit profile page :)
=> Remove link to edit profile page when already editing profile

.gitignore
=> Exclude custom theme from git tracking

src/main/java/org/mamute/controllers/AnswerController.java, src/main/java/org/mamute/dao/AnswerDAO.java, src/main/java/org/mamute/model/Answer.java, src/main/java/org/mamute/model/AnswerCommentList.java, src/main/java/org/mamute/model/Question.java, src/main/resources/development/hibernate.cfg.xml, src/main/resources/mamute.properties, src/main/resources/routes.properties, src/main/webapp/WEB-INF/tags/answerWith.tag, src/main/webapp/WEB-INF/tags/questionWith.tag, src/main/webapp/assets/js/delete-question.js
Now we can authors can soft delete answers too @leocwolter  :-)
=> Deletable answers

pom.xml, src/main/java/org/mamute/controllers/UserProfileController.java, src/main/java/org/mamute/filesystem/AttachmentsFileStorage.java, src/main/java/org/mamute/model/Attachment.java, src/main/resources/mamute-messages.properties, src/main/webapp/assets/js/avatarupload.js
@leocwolter @MatejBalantic 
The intention of this PR is to support scaling of the uploaded avatars but it also fixes https://github.com/caelum/mamute/issues/158.
=> Scaling avatars

src/main/java/org/mamute/controllers/CommentController.java, src/main/java/org/mamute/dao/CommentDAO.java, src/main/java/org/mamute/model/Answer.java, src/main/java/org/mamute/model/AnswerCommentList.java, src/main/java/org/mamute/model/Comment.java, src/main/java/org/mamute/model/News.java, src/main/java/org/mamute/model/NewsCommentList.java, src/main/java/org/mamute/model/Post.java, src/main/java/org/mamute/model/Question.java, src/main/java/org/mamute/model/QuestionCommentList.java, src/main/resources/development/hibernate.cfg.xml, src/main/resources/mamute.properties, src/main/resources/routes.properties, src/main/webapp/WEB-INF/jsp/brutalTemplates/comment.jspf, src/main/webapp/WEB-INF/tags/add-a-comment.tag, src/main/webapp/WEB-INF/tags/commentWith.tag, src/main/webapp/assets/js/delete-question.js
@leocwolter this adds the capability of users to delete their own comments.
=> Deletable comments

src/main/resources/mamute-messages_de.properties
Some things like date formats are not properly localized in Mamute, but everything that can be translated is done.
=> Added German localization

src/main/java/org/mamute/auth/LDAPApi.java
Support for fetching user avatars from LDAP. Configure this by configuring mamute for LDAP and additionally setting 
```
ldap.avatarImageAttr=thumbnailPhoto
```
or 
```
ldap.avatarImageAttr=jpegPhoto
```
At the moment, the user avatar is fetched upon every login. If this would be too much for large sites, one would need some mechanism to do this only once in a while or check whether the image has actually changed.
=> Fetch jpegPhoto or thumbnailPhoto as avatar image from LDAP

pom.xml, src/test/java/org/mamute/dao/TagDAOTest.java, src/test/java/org/mamute/dao/WithUserPaginatedDAOTest.java, src/test/java/org/mamute/infra/rss/QuestionRssEntryFactoryTest.java, src/test/java/org/mamute/validators/UserPersonalInfoValidatorTest.java
This will probably fix our tests running at travis and I'm also removing jacoco for now since this plugin version it's not working with jdk 8.
=> Fixing tests by reseting current time

src/main/resources/mamute-messages.properties, src/main/resources/mamute-messages_pt_BR.properties, src/main/webapp/WEB-INF/tags/answerWith.tag, src/main/webapp/WEB-INF/tags/newsWith.tag, src/main/webapp/WEB-INF/tags/questionWith.tag
While translating Mamute to German, I found and fixed a few things in the English messages.
=> Some corrections of the English localization

docker/production/Mamute/Dockerfile, docker/production/Mamute/production.properties, docker/production/Nginx/conf.d/test.conf, docker/production/Nginx/nginx.conf, docker/production/Readme.md, docker/production/docker-compose.yml
As requested by Leonardo Wolter, here's a complete production configuration of Mamute with Docker and Docker-Compose. It's running out of the box, only the first start is a bit slow due to database initialization.
Further informaton and a basic usage tutorial can be found in the Readme.md file inside `docker/production/`.
=> Added Docker and Docker-Compose Configuration

src/main/resources/mamute-messages.properties, src/main/resources/mamute-messages_de.properties, src/main/resources/mamute-messages_pt_BR.properties, src/main/webapp/WEB-INF/tags/historiesSelect.tag
Can also be seen here for example (top right corner): http://meta.mamute.org/396/history
=> Make the version selection dropdown translatable on the question history

src/main/java/org/mamute/controllers/UserProfileController.java, src/main/java/org/mamute/converters/BrutalDateTimeConverter.java, src/main/webapp/WEB-INF/jsp/antiHack/massiveVotesForm.jsp, src/main/webapp/WEB-INF/jsp/coda.jspf, src/main/webapp/WEB-INF/jsp/userProfile/editProfile.jsp, src/main/webapp/WEB-INF/tags/dateInput.tag, src/main/webapp/WEB-INF/tags/jodaTime.tag, src/main/webapp/assets/js/form-validation.js, src/test/java/org/mamute/converters/BrutalDateTimeConverterTest.java
This fixes two issues:
1. changing the birthdate
2. allows users to leave the website field blank
=> Fix changing profile

src/main/webapp/WEB-INF/tags/detailsList.tag, src/main/webapp/WEB-INF/tags/editedTouch.tag, src/main/webapp/WEB-INF/tags/touchesFor.tag, src/main/webapp/WEB-INF/web.xml
This adds preliminary Tomcat 8 compatibility.
Only a few quick tests were done, but everything seems to work fine so far.
=> Preliminary Tomcat 8 compatibility

src/main/webapp/WEB-INF/web.xml
This reverts commit 71f14756c8576172c48123d6017dbfc67ee24799.
Fixes #226
=> Revert "Add the DefaultServlet in web.xml to allow HTTP PUT and DELETE"

src/main/resources/mamute-messages.properties
Removed one accent that was causing problems with some English editors
=> Some minor changes for more natural sounding English

src/main/java/org/mamute/security/CORSController.java
=> implementing CORS controller

src/main/resources/mamute-messages.properties, src/main/resources/mamute-messages_de.properties, src/main/resources/mamute-messages_pt_BR.properties, src/main/webapp/404.jsp
=> Remove the non-existing search link from the 404 page

src/main/java/org/mamute/sanitizer/HtmlElement.java, src/main/java/org/mamute/sanitizer/HtmlElementsBuilder.java, src/main/java/org/mamute/sanitizer/HtmlLinkTargetElementPolicy.java, src/main/java/org/mamute/sanitizer/MamutePolicyProducer.java, src/test/java/org/mamute/sanitizer/HtmlSanitizerTest.java
This implements #82 
We should discuss how HtmlElementsBuilder finds the correct ElementPolicy for an element.
My current implementation is just a demo which shows that it's possible to implement the functionality from #82.
=> Always add target="_blank" to links in our sanitized HTML

pom.xml
intellij idea doesn't detect that src/integration/java is a test source directory.
=> add integration directory as test source. (intellij idea errors)

src/main/java/org/mamute/dao/ReputationEventDAO.java
Fix for issue https://github.com/caelum/mamute/issues/261
=> Fixing error with in view profile page

src/main/resources/log4j.xml
Cleans up a warning due to a missing appender
=> Add log4j appender declaration to clean up mchange warning

src/main/webapp/WEB-INF/jsp/navigation/about.jsp
This PR should ifx issue #287 .
=> fix: typo in permission rule name in about page (#287)

.travis.yml, README.md
=> Add documentation on how to start a release instance of Mamute.
